export type Profile = {
  id: string;
  household_id: string | null;
  email: string;
  full_name: string | null;
  role: 'client' | 'staff' | 'admin';
  avatar_path: string | null;
};

export type Pet = {
  id: string;
  household_id: string;
  name: string;
  species: 'dog' | 'cat' | 'other' | null;
  breed: string | null;
  photo_path: string | null;
};

export type PetFood = {
  id: string;
  pet_id: string;
  brand: string | null;
  product_name: string;
  package_size_g: number | null;
  daily_amount_g: number | null;
  last_purchased_on: string | null;
  /** Generated by the database from bag size, daily amount and last purchase. */
  depletes_on: string | null;
  active: boolean;
};

export type PetMedication = {
  id: string;
  pet_id: string;
  name: string;
  dose: string | null;
  frequency: string | null;
  last_filled_on: string | null;
  days_supply: number | null;
  is_preventative: boolean;
  depletes_on: string | null;
  active: boolean;
};

export type Vaccination = {
  id: string;
  pet_id: string;
  vaccine_name: string;
  administered_on: string;
  next_due_on: string | null;
};

/** What the desk taps at checkout. Per event, never per dollar. */
export type EarnRule = {
  id: string;
  code: string;
  label: string;
  points: number;
  active: boolean;
};

export type Reward = {
  id: string;
  label: string;
  points_cost: number;
  active: boolean;
};

/**
 * One line of the append-only ledger. There is no stored balance anywhere:
 * `points_balances` sums this, and a correction is an offsetting row rather
 * than an edit, so every point a client holds can be accounted for.
 */
export type LedgerRow = {
  id: string;
  delta: number;
  reason: string;
  created_at: string;
  earn_rule_id: string | null;
  pets: { name: string } | null;
};

export type RequestType = 'food' | 'medication' | 'other';

export type RequestStatus =
  | 'submitted'
  | 'in_review'
  | 'approved'
  | 'ready'
  | 'completed'
  | 'declined';

export type ClientRequest = {
  id: string;
  pet_id: string | null;
  type: RequestType;
  status: RequestStatus;
  details: { item?: string; quantity?: string };
  client_note: string | null;
  staff_note: string | null;
  created_at: string;
};

// Each status gets a distinct stamp SHAPE (solid, dashed, doubled, filled,
// struck) so state survives colour blindness and greyscale. Nothing here
// depends on hue alone. See .stamp-* in styles.css.
export const STATUS_STAMP: Record<RequestStatus, string> = {
  submitted: 'stamp-sent',
  in_review: 'stamp-review',
  approved: 'stamp-approved',
  ready: 'stamp-ready',
  completed: 'stamp-done',
  declined: 'stamp-declined',
};

// What a staff member is about to DO, in the imperative. The stamps below name
// states; these name actions. Using one wording for both put a button reading
// "Approved" next to a stamp reading "Being looked at", which says nothing
// about what pressing it does.
export const ACTION_LABEL: Record<RequestStatus, string> = {
  submitted: 'Reopen',
  in_review: 'Review',
  approved: 'Approve',
  ready: 'Mark ready',
  completed: 'Hand over',
  declined: 'Decline',
};

// What pressing it does to the request, as a tone rather than a state. The
// stamps beside these buttons carry state by SHAPE and keep doing so; this only
// separates the two things the desk needs to tell apart at a glance across a
// counter: the button that moves a request toward the client getting their
// thing, and the one that refuses it. Picking a request up is neither, so
// Review and Reopen stay in the document's own ink.
export const ACTION_TONE: Record<RequestStatus, string> = {
  submitted: '',
  in_review: '',
  approved: 'act-go',
  ready: 'act-go',
  completed: 'act-go',
  declined: 'act-stop',
};

// Wording the client sees. The raw status values are for staff.
export const STATUS_LABEL: Record<RequestStatus, string> = {
  submitted: 'Sent',
  in_review: 'Being looked at',
  approved: 'Approved',
  ready: 'Ready for pickup',
  completed: 'Picked up',
  declined: 'Not approved',
};
