export type Profile = {
  id: string;
  household_id: string | null;
  email: string;
  full_name: string | null;
  role: 'client' | 'staff' | 'admin';
};

export type Pet = {
  id: string;
  household_id: string;
  name: string;
  species: 'dog' | 'cat' | 'other' | null;
  breed: string | null;
  photo_path: string | null;
};

export type PetFood = {
  id: string;
  pet_id: string;
  brand: string | null;
  product_name: string;
  package_size_g: number | null;
  daily_amount_g: number | null;
  last_purchased_on: string | null;
  /** Generated by the database from bag size, daily amount and last purchase. */
  depletes_on: string | null;
  active: boolean;
};

export type PetMedication = {
  id: string;
  pet_id: string;
  name: string;
  dose: string | null;
  frequency: string | null;
  last_filled_on: string | null;
  days_supply: number | null;
  is_preventative: boolean;
  depletes_on: string | null;
  active: boolean;
};

export type Vaccination = {
  id: string;
  pet_id: string;
  vaccine_name: string;
  administered_on: string;
  next_due_on: string | null;
};

export type RequestType = 'food' | 'medication' | 'other';

export type RequestStatus =
  | 'submitted'
  | 'in_review'
  | 'approved'
  | 'ready'
  | 'completed'
  | 'declined';

export type ClientRequest = {
  id: string;
  pet_id: string | null;
  type: RequestType;
  status: RequestStatus;
  details: { item?: string; quantity?: string };
  client_note: string | null;
  staff_note: string | null;
  created_at: string;
};

// Wording the client sees. The raw status values are for staff.
export const STATUS_LABEL: Record<RequestStatus, string> = {
  submitted: 'Sent',
  in_review: 'Being looked at',
  approved: 'Approved',
  ready: 'Ready for pickup',
  completed: 'Picked up',
  declined: 'Not approved',
};
